spring:
  application:
    name: smart-home-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 19999
  servlet:
    context-path: /api

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
